import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ClerkProvider, SignedIn, SignedOut, SignInButton, SignOutButton, SignUpButton, UserButton } from "@clerk/nextjs";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // <ClerkProvider>
      <html lang="en">
        <head>
          <meta charSet="UTF-8" />
        </head>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
       {/* <header className="flex items-center justify-between p-4 bg-neutral-800 shadow-md">
            <div className="flex gap-3 items-center">
              <SignedOut>
                <div className="flex justify-end gap-2">
                <SignInButton>
                  <button className="bg-white">Sign In</button>
                </SignInButton>
                </div>
              </SignedOut>
              <SignedIn>
                <UserButton />
              </SignedIn>
            </div>
          </header> */}
          {/* <SignedIn> */}
          {children}
          {/* </SignedIn> */}
      </body>
    </html>
    // </ClerkProvider>

  );
}
